import { ArrowUpRight, MapPin, Sprout } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Prediction, Profile } from '../api/types'

export function FarmPage({ history, profile }: { history: Prediction[]; profile?: Profile | null }) {
  const latest = history[0]
  return <section className="farm-page"><div className="section-head"><div><p className="eyebrow">Your growing ground</p><h1>My farm</h1></div><button className="outline"><MapPin size={15} /> Edit details</button></div><div className="farm-overview"><div><p className="eyebrow">Home location</p><h2>{profile?.location ?? 'Anand, Gujarat'}</h2><p>Monsoon season · 2026</p></div><div className="farm-number"><strong>3</strong><span>plots in rotation</span></div><div className="farm-number"><strong>8.2</strong><span>acres mapped</span></div></div><div className="section-head compact"><div><p className="eyebrow">Your zones</p><h2>Plots at a glance</h2></div></div><div className="plot-grid"><Plot name="North Plot" crop="Tomato" area="2.4 acres" health="Attention" latest={latest?.disease.label ?? 'Aphids'} /><Plot name="East Plot" crop="Cotton" area="3.1 acres" health="Healthy" latest="No recent concern" /><Plot name="South Plot" crop="Potato" area="2.7 acres" health="Healthy" latest="Clear" /></div><div className="crop-history"><Sprout size={19} /><div><p className="eyebrow">Crop history</p><h3>What has grown here</h3><p>2026 · Tomato &nbsp; / &nbsp; 2025 · Cotton &nbsp; / &nbsp; 2024 · Groundnut</p></div><Link to="/history"><ArrowUpRight size={17} /></Link></div></section>
}
function Plot({ name, crop, area, health, latest }: { name: string; crop: string; area: string; health: string; latest: string }) { return <article className="plot-card"><div className="plot-header"><span className={`plot-health ${health === 'Healthy' ? 'good' : 'watch'}`}>{health}</span><MapPin size={16} /></div><h3>{name}</h3><p className="plot-crop">{crop}</p><div className="plot-data"><span>Area <b>{area}</b></span><span>Latest <b>{latest}</b></span></div><Link to="/history">View plot history <ArrowUpRight size={15} /></Link></article> }
